spring:
  application:
    name: kafka-streams-service
  profiles:
    active: kafka_streams
  cloud:
    config:
      name: kafka-streams-service,config-client
      username: spring_cloud_user
      password: '{cipher}0dbba6b61e4e061ca3ee152c47ed93aac50292169027f1f5b8ef13ad188162ddd50a1f43fbc1ab1339d312b11deb4f21'
  config:
    import: 'configserver:'

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service-1:8761/eureka/
  # only needed for gateway-service implementation
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2