twitter-to-kafka-service:
  enable-mock-tweets: true
#here we set app name for service discovery, active profile for getting config files from git using spring cloud
#config server, config name, that is composed like {prefix-active_profile} creds and uri to get config
spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      username: spring_cloud_user
      password: '{cipher}0dbba6b61e4e061ca3ee152c47ed93aac50292169027f1f5b8ef13ad188162ddd50a1f43fbc1ab1339d312b11deb4f21'