spring:
  application:
    name: reactive-elastic-query-service
  profiles:
    active: reactive_elastic_query
  cloud:
    config:
      name: reactive-elastic-query-service,config-client
      username: spring_cloud_user
      password: '{cipher}0dbba6b61e4e061ca3ee152c47ed93aac50292169027f1f5b8ef13ad188162ddd50a1f43fbc1ab1339d312b11deb4f21'
  config:
    import: 'configserver:'
